Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,7 +29,7 @@ jobs:
           if [[ $(cat my_workspace/echo-output) == 'Trying out workspaces' ]]; then
             echo "It worked!";
           else
-            echo "It failed!";
+            echo "It failed!"; exit 1
           fi
 
   deploy:  
